version: '3.9'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    command: [ 'python3', 'manage.py', 'runserver', '0.0.0.0:8000' ]
    depends_on:
      - pg_db
    env_file:
      - env.dev
  pg_db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=shop
      - POSTGRES_PASSWORD=shop
      - POSTGRES_DB=shop_dev
    ports:
      - "5432:5432"
  flower:
    image: mher/flower:0.9.5
    command: [ 'flower', '--broker=redis://redis:6379', '--port=5555' ]
    ports:
      - "5557:5555"
    depends_on:
      - redis
volumes:
  postgres_data:

