version: '3.9'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    command: [ 'python3', 'manage.py', 'runserver', '0.0.0.0:8000' ]
    depends_on:
      - pg_db
    env_file:
      - env.dev
  pg_db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=11081998
      - POSTGRES_DB=shop_dev
    ports:
      - "5432:5432"
  celery:
    build: .
    command: celery -A projectshop worker -l INFO
    env_file:
      - env.dev
    depends_on:
      - redis
      - web
  celery-beat:
    build: .
    command: celery -A projectshop beat -l INFO
    env_file:
      - env.dev
    depends_on:
      - web
      - redis
  flower:
    build: .
    command: celery -A projectshop flower --address=0.0.0.0 --port=5566
    ports:
      - "5566:5566"
    depends_on:
      - redis
      - celery
      - web
volumes:
  postgres_data:

