# Generated by Django 3.2.11 on 2022-03-29 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(verbose_name='Номер заказа')),
                ('subject', models.CharField(choices=[('Информация по заказу', 'Информация по заказу'), ('Коммерческое предложение', 'Коммерческое предложение'), ('Консультация по товару', 'Консультация по товару'), ('Дисконтные карты', 'Дисконтные карты'), ('Обмен и возврат товара', 'Обмен и возврат товара'), ('Вопросы по браку и гарантии', 'Вопросы по браку и гарантии'), ('Отзыв о компании', 'Отзыв о компании'), ('Предложение сотрудничества', 'Предложение сотрудничества'), ('Работа в ноябре', 'Работа в ноябре'), ('Ошибка на сайте', 'Ошибка на сайте'), ('Перезвонить', 'Перезвонить')], max_length=256, verbose_name='Тема обращения')),
                ('text', models.TextField(verbose_name='Текст обращения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('Обращение открыто', 'Обращение открыто'), ('Обращение закрыто', 'Обращение закрыто')], default='Обращение открыто', max_length=256, verbose_name='Статус обращения')),
                ('indicator', models.CharField(choices=[('green', 'green'), ('red', 'red'), ('grey', 'grey')], default='green', max_length=256, verbose_name='Индикатор обращения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ticket', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(verbose_name='Сообщение')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_msg', to='tickets.ticket', verbose_name='Сообщение в обращении')),
            ],
            options={
                'verbose_name': 'Сообщения в обращении',
                'verbose_name_plural': 'Сообщения в обращениях',
            },
        ),
    ]
