# Generated by Django 3.2.11 on 2022-01-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_type',
            field=models.CharField(choices=[('Онлайн', 'Онлайн'), ('При получении', 'При получении')], default='Онлайн', max_length=50, verbose_name='Тип оплаты'),
        ),
    ]
